---
title: "Wrangle Model Data"
author: "Tyler Hill"
date: "4/9/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r message=F, warning=F}
# Load libraries
library(tidyverse)
```

***

## Load, inspect, and clean the data from the tutorial

```{r}
# Data from https://data-flair.training/blogs/advanced-python-project-detecting-fake-news/
news_data <- read.csv("./data/data-flair/news.csv")
# View(news_data)

# Drop the X column
news_data <- news_data %>% select(!c(X, title))
```

## Load, inspect, clean, and merge the data from the ISOT data set with the tutorial data

```{r}
# Data from https://www.uvic.ca/engineering/ece/isot/datasets/fake-news/index.php
# Fake news
isot_fake_data <- read.csv("./data/ISOT-data/Fake.csv")
# View(isot_fake_data)
isot_fake_data <- isot_fake_data %>% 
  select(!c(title, subject, date)) %>% 
  mutate(label = "FAKE")

# True news
isot_true_data <- read.csv("./data/ISOT-data/True.csv")
# View(isot_true_data)
isot_true_data <- isot_true_data %>% 
  select(!c(title, subject, date)) %>% 
  mutate(label = "REAL")

isot <- bind_rows(isot_fake_data, isot_true_data)
```

## Load fake news data sets from kaggle

```{r}
# Data from https://www.kaggle.com/c/fakenewskdd2020
kag_2020 <- read.csv("./data/kaggle-fakenewskdd2020/train.csv", sep = "\t", quote = "")
# View(kag_2020)

# Drop rows where text is too short
kag_2020 <- kag_2020 %>%
  mutate(label = ifelse(label == 0, "REAL", "FAKE"))
```

```{r}
# Data from https://www.kaggle.com/c/fake-news
kag_2018 <- read.csv("./data/kaggle-fake-news/train.csv")
# View(kag_2018)

# Drop rows where text is too short
kag_2018 <- kag_2018 %>%
  select(text, label) %>% 
  mutate(label = ifelse(label == 0, "REAL", "FAKE"))
```

```{r}
# Data from https://www.kaggle.com/c/classifying-the-fake-news
kag_2017 <- read.csv("./data/kaggle-classify/training.csv")
# View(kag_2017)

# Drop rows where text is too short
kag_2017 <- kag_2017 %>%
  select(text, label) %>% 
  mutate(label = ifelse(label == 0, "REAL", "FAKE"))
```

## Merge the data sets and clean them

```{r}
# Merge
data <- bind_rows(news_data, isot)
data <- bind_rows(data, kag_2020)
data <- bind_rows(data, kag_2018)
data <- bind_rows(data, kag_2017)
# View(data)

# Clean
data <- data %>% 
  mutate(
    text = ifelse(
      lengths(strsplit(text, " ")) < 50,
      NA,
      text
    )
  ) %>% 
  drop_na() %>% 
  unique()
```

## Save to a single file

```{r}
write.csv(data, "./data/data.csv", row.names = FALSE)
```

```{r}
#rm(list = ls())
```

